// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppBlaze.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// update_G_Rcpp
Rcpp::NumericMatrix update_G_Rcpp(Rcpp::NumericMatrix adj, Rcpp::NumericMatrix edge_prob_mat, double df, double df_0, Rcpp::NumericMatrix rate, int n_edge, int seed, bool approx, bool delayed_accept, bool loc_bal);
RcppExport SEXP _WWA_update_G_Rcpp(SEXP adjSEXP, SEXP edge_prob_matSEXP, SEXP dfSEXP, SEXP df_0SEXP, SEXP rateSEXP, SEXP n_edgeSEXP, SEXP seedSEXP, SEXP approxSEXP, SEXP delayed_acceptSEXP, SEXP loc_balSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type edge_prob_mat(edge_prob_matSEXP);
    Rcpp::traits::input_parameter< double >::type df(dfSEXP);
    Rcpp::traits::input_parameter< double >::type df_0(df_0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< int >::type n_edge(n_edgeSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type approx(approxSEXP);
    Rcpp::traits::input_parameter< bool >::type delayed_accept(delayed_acceptSEXP);
    Rcpp::traits::input_parameter< bool >::type loc_bal(loc_balSEXP);
    rcpp_result_gen = Rcpp::wrap(update_G_Rcpp(adj, edge_prob_mat, df, df_0, rate, n_edge, seed, approx, delayed_accept, loc_bal));
    return rcpp_result_gen;
END_RCPP
}
// rgwish_Rcpp
Rcpp::NumericMatrix rgwish_Rcpp(Rcpp::NumericMatrix adj, double df, Rcpp::NumericMatrix rate, int seed);
RcppExport SEXP _WWA_rgwish_Rcpp(SEXP adjSEXP, SEXP dfSEXP, SEXP rateSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< double >::type df(dfSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(rgwish_Rcpp(adj, df, rate, seed));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _WWA_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_WWA_update_G_Rcpp", (DL_FUNC) &_WWA_update_G_Rcpp, 10},
    {"_WWA_rgwish_Rcpp", (DL_FUNC) &_WWA_rgwish_Rcpp, 4},
    {"_WWA_rcpp_hello_world", (DL_FUNC) &_WWA_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_WWA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
