# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_G_Rcpp <- function(adj, edge_prob_mat, df, df_0, rate, n_edge, seed, approx = FALSE, delayed_accept = TRUE, loc_bal = TRUE) {
    .Call(`_WWA_update_G_Rcpp`, adj, edge_prob_mat, df, df_0, rate, n_edge, seed, approx, delayed_accept, loc_bal)
}

rgwish_Rcpp <- function(adj, df, rate, seed) {
    .Call(`_WWA_rgwish_Rcpp`, adj, df, rate, seed)
}

rcpp_hello_world <- function() {
    .Call(`_WWA_rcpp_hello_world`)
}

